#AnimatedDoors client config
#Sat Jul 25 11:31:53 CEST 2026
animationDurationSeconds=0.30
connectedBlocksOnServersEnabled=true
connectedDoorsEnabled=true
connectedFenceGatesEnabled=true
connectedTrapdoorsEnabled=true
doorsEnabled=true
easing=ease_in_out
fenceGatesEnabled=true
trapdoorsEnabled=true
